import Medicine from '../models/Medicine.js';

export const INITIAL_MEDICINES = [
  {
    name: 'Paracetamol 500mg',
    genericName: 'Paracetamol',
    category: 'Tablet',
    manufacturer: 'GSK Healthcare',
    strength: '500mg',
    dosageForm: 'Tablet',
    batchNumber: 'PCM-2026-01',
    expiryDate: new Date('2028-12-31'),
    quantity: 1000,
    reorderLevel: 200,
    unitPrice: 15.00,
    description: 'Analgesic and antipyretic for pain and fever relief.',
    isActive: true,
  },
  {
    name: 'Amoxicillin 500mg',
    genericName: 'Amoxicillin',
    category: 'Capsule',
    manufacturer: 'Cipla Ltd',
    strength: '500mg',
    dosageForm: 'Capsule',
    batchNumber: 'AMX-2026-02',
    expiryDate: new Date('2027-10-15'),
    quantity: 500,
    reorderLevel: 150,
    unitPrice: 25.00,
    description: 'Broad-spectrum penicillin antibiotic.',
    isActive: true,
  },
  {
    name: 'Azithromycin 250mg',
    genericName: 'Azithromycin',
    category: 'Tablet',
    manufacturer: 'Pfizer Inc',
    strength: '250mg',
    dosageForm: 'Tablet',
    batchNumber: 'AZM-2026-03',
    expiryDate: new Date('2027-08-20'),
    quantity: 300,
    reorderLevel: 100,
    unitPrice: 45.00,
    description: 'Macrolide antibiotic for respiratory and skin infections.',
    isActive: true,
  },
  {
    name: 'Cetirizine 10mg',
    genericName: 'Cetirizine Hydrochloride',
    category: 'Tablet',
    manufacturer: 'Dr. Reddys',
    strength: '10mg',
    dosageForm: 'Tablet',
    batchNumber: 'CTZ-2026-04',
    expiryDate: new Date('2028-05-10'),
    quantity: 800,
    reorderLevel: 150,
    unitPrice: 8.50,
    description: 'Second-generation antihistamine for allergies.',
    isActive: true,
  },
  {
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole',
    category: 'Capsule',
    manufacturer: 'Sun Pharma',
    strength: '20mg',
    dosageForm: 'Capsule',
    batchNumber: 'OMP-2026-05',
    expiryDate: new Date('2027-12-01'),
    quantity: 400,
    reorderLevel: 100,
    unitPrice: 18.00,
    description: 'Proton-pump inhibitor for acid reflux and ulcers.',
    isActive: true,
  },
  {
    name: 'Pantoprazole 40mg',
    genericName: 'Pantoprazole Sodium',
    category: 'Tablet',
    manufacturer: 'Alkem Labs',
    strength: '40mg',
    dosageForm: 'Tablet',
    batchNumber: 'PNT-2026-06',
    expiryDate: new Date('2028-03-25'),
    quantity: 600,
    reorderLevel: 150,
    unitPrice: 22.00,
    description: 'Gastric acid secretion reducer.',
    isActive: true,
  },
  {
    name: 'Metformin 500mg',
    genericName: 'Metformin Hydrochloride',
    category: 'Tablet',
    manufacturer: 'USV Pharma',
    strength: '500mg',
    dosageForm: 'Tablet',
    batchNumber: 'MET-2026-07',
    expiryDate: new Date('2028-09-14'),
    quantity: 1200,
    reorderLevel: 300,
    unitPrice: 12.00,
    description: 'First-line medication for type 2 diabetes.',
    isActive: true,
  },
  {
    name: 'Amlodipine 5mg',
    genericName: 'Amlodipine Besylate',
    category: 'Tablet',
    manufacturer: 'Torrent Pharma',
    strength: '5mg',
    dosageForm: 'Tablet',
    batchNumber: 'AML-2026-08',
    expiryDate: new Date('2027-11-30'),
    quantity: 750,
    reorderLevel: 200,
    unitPrice: 14.00,
    description: 'Calcium channel blocker for hypertension.',
    isActive: true,
  },
  {
    name: 'ORS Electrolyte Powder',
    genericName: 'Oral Rehydration Salts',
    category: 'Powder',
    manufacturer: 'FDC Limited',
    strength: '21.8g',
    dosageForm: 'Powder',
    batchNumber: 'ORS-2026-09',
    expiryDate: new Date('2029-01-01'),
    quantity: 350,
    reorderLevel: 100,
    unitPrice: 20.00,
    description: 'WHO formula oral rehydration powder.',
    isActive: true,
  },
  {
    name: 'Salbutamol Inhaler 100mcg',
    genericName: 'Salbutamol / Albuterol',
    category: 'Inhaler',
    manufacturer: 'Cipla Respiratory',
    strength: '100mcg/dose',
    dosageForm: 'Inhaler',
    batchNumber: 'SBT-2026-10',
    expiryDate: new Date('2027-07-07'),
    quantity: 150,
    reorderLevel: 50,
    unitPrice: 180.00,
    description: 'Short-acting beta2-adrenergic agonist bronchodilator.',
    isActive: true,
  },
  {
    name: 'Vitamin B Complex',
    genericName: 'B-Complex with Vitamin C',
    category: 'Capsule',
    manufacturer: 'Abbott Healthcare',
    strength: 'Standard',
    dosageForm: 'Capsule',
    batchNumber: 'VBC-2026-11',
    expiryDate: new Date('2028-04-18'),
    quantity: 900,
    reorderLevel: 200,
    unitPrice: 16.50,
    description: 'Essential multivitamin nutritional supplement.',
    isActive: true,
  },
  {
    name: 'Ibuprofen 400mg',
    genericName: 'Ibuprofen',
    category: 'Tablet',
    manufacturer: 'Abbott Labs',
    strength: '400mg',
    dosageForm: 'Tablet',
    batchNumber: 'IBU-2026-12',
    expiryDate: new Date('2028-06-30'),
    quantity: 650,
    reorderLevel: 150,
    unitPrice: 18.50,
    description: 'Nonsteroidal anti-inflammatory drug (NSAID).',
    isActive: true,
  },
];

export const seedPharmacy = async () => {
  try {
    for (const medData of INITIAL_MEDICINES) {
      await Medicine.findOneAndUpdate(
        { name: medData.name, batchNumber: medData.batchNumber },
        { $setOnInsert: medData },
        { upsert: true, new: true }
      );
    }
    console.log('Pharmacy medicines seeded/verified successfully (12 formulations).');
  } catch (error) {
    console.error('Error seeding pharmacy medicines:', error);
  }
};
